grpc-endpoint = "0.0.0.0:4446"

[log]
level = "debug"
outputs = []
format = "json"

[telemetry]
prometheus-addr = "0.0.0.0:9090"

[shutdown]
runtime-timeout = "5s"

[aggchain-proof-service.aggchain-proof-builder]
network-id = @@replace

[aggchain-proof-service.aggchain-proof-builder.primary-prover.network-prover]
proving-timeout = "1h"

[aggchain-proof-service.aggchain-proof-builder.proving-timeout]
secs = 3600
nanos = 0

[aggchain-proof-service.aggchain-proof-builder.contracts]
l1-rpc-endpoint = "@@replace"
l2-execution-layer-rpc-endpoint = "@@replace"
l2-consensus-layer-rpc-endpoint = "@@replace"
polygon-rollup-manager = "@@replace"
global-exit-root-manager-v2-sovereign-chain = "@@replace"

[aggchain-proof-service.proposer-service]
l1-rpc-endpoint = "@@replace"
mock = false

[aggchain-proof-service.proposer-service.client]
proposer-endpoint = "@@replace"
sp1-cluster-endpoint = "@@replace"
request-timeout = 3600
proving-timeout = 3600

[primary-prover.network-prover]
proving-timeout = "1h"
